// This file is part of the ACTS project.
//
// Copyright (C) 2016 CERN for the benefit of the ACTS project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Note: This file is generated by generate_sympy_jac.py
//       Do not modify it manually.

#pragma once

#include <cmath>

template <typename T>
void boundToBoundTransportJacobianImpl(const T* J_fb, const T* J_t,
                                       const T* J_bf,
                                       const T* step_path_derivatives,
                                       const T* surface_path_derivatives,
                                       T* J_full) {
  const auto x0 = J_fb[5] * step_path_derivatives[1];
  const auto x1 = J_fb[10] * step_path_derivatives[2];
  const auto x2 = step_path_derivatives[0] * surface_path_derivatives[0] + 1;
  const auto x4 = J_fb[0] * step_path_derivatives[0];
  const auto x5 = step_path_derivatives[1] * surface_path_derivatives[1] + 1;
  const auto x7 = step_path_derivatives[2] * surface_path_derivatives[2] + 1;
  const auto x15 = J_fb[6] * step_path_derivatives[1];
  const auto x16 = J_fb[11] * step_path_derivatives[2];
  const auto x18 = J_fb[1] * step_path_derivatives[0];
  const auto x27 = J_fb[17] * step_path_derivatives[3];
  const auto x28 = J_fb[22] * step_path_derivatives[4];
  const auto x29 = J_fb[27] * step_path_derivatives[5];
  const auto x33 = step_path_derivatives[3] * surface_path_derivatives[3] + 1;
  const auto x35 = step_path_derivatives[4] * surface_path_derivatives[4] + 1;
  const auto x37 = step_path_derivatives[5] * surface_path_derivatives[5] + 1;
  const auto x42 = J_fb[18] * step_path_derivatives[3];
  const auto x43 = J_fb[23] * step_path_derivatives[4];
  const auto x44 = J_fb[28] * step_path_derivatives[5];
  const auto x9 = (x0 + x1 + x4) * surface_path_derivatives[3];
  const auto x10 = (x0 + x1 + x4) * surface_path_derivatives[4];
  const auto x11 = (x0 + x1 + x4) * surface_path_derivatives[5];
  const auto x21 = (x15 + x16 + x18) * surface_path_derivatives[3];
  const auto x22 = (x15 + x16 + x18) * surface_path_derivatives[4];
  const auto x23 = (x15 + x16 + x18) * surface_path_derivatives[5];
  const auto x30 = (x27 + x28 + x29) * surface_path_derivatives[0];
  const auto x31 = (x27 + x28 + x29) * surface_path_derivatives[1];
  const auto x32 = (x27 + x28 + x29) * surface_path_derivatives[2];
  const auto x45 = (x42 + x43 + x44) * surface_path_derivatives[0];
  const auto x46 = (x42 + x43 + x44) * surface_path_derivatives[1];
  const auto x47 = (x42 + x43 + x44) * surface_path_derivatives[2];
  const auto x3 = x0 * surface_path_derivatives[0] +
                  x1 * surface_path_derivatives[0] + x2 * J_fb[0];
  const auto x6 = x1 * surface_path_derivatives[1] +
                  x4 * surface_path_derivatives[1] + x5 * J_fb[5];
  const auto x8 = x0 * surface_path_derivatives[2] +
                  x4 * surface_path_derivatives[2] + x7 * J_fb[10];
  const auto x17 = x15 * surface_path_derivatives[0] +
                   x16 * surface_path_derivatives[0] + x2 * J_fb[1];
  const auto x19 = x16 * surface_path_derivatives[1] +
                   x18 * surface_path_derivatives[1] + x5 * J_fb[6];
  const auto x20 = x15 * surface_path_derivatives[2] +
                   x18 * surface_path_derivatives[2] + x7 * J_fb[11];
  const auto x34 = x28 * surface_path_derivatives[3] +
                   x29 * surface_path_derivatives[3] + x33 * J_fb[17];
  const auto x36 = x27 * surface_path_derivatives[4] +
                   x29 * surface_path_derivatives[4] + x35 * J_fb[22];
  const auto x38 = x27 * surface_path_derivatives[5] +
                   x28 * surface_path_derivatives[5] + x37 * J_fb[27];
  const auto x48 = x33 * J_fb[18] + x43 * surface_path_derivatives[3] +
                   x44 * surface_path_derivatives[3];
  const auto x49 = x35 * J_fb[23] + x42 * surface_path_derivatives[4] +
                   x44 * surface_path_derivatives[4];
  const auto x50 = x37 * J_fb[28] + x42 * surface_path_derivatives[5] +
                   x43 * surface_path_derivatives[5];
  const auto x12 = x10 * J_t[25] + x11 * J_t[26] + x3 * J_t[21] + x6 * J_t[22] +
                   x8 * J_t[23] + x9 * J_t[24];
  const auto x13 = x10 * J_t[32] + x11 * J_t[33] + x3 * J_t[28] + x6 * J_t[29] +
                   x8 * J_t[30] + x9 * J_t[31];
  const auto x14 = x10 * J_t[39] + x11 * J_t[40] + x3 * J_t[35] + x6 * J_t[36] +
                   x8 * J_t[37] + x9 * J_t[38];
  const auto x24 = x17 * J_t[21] + x19 * J_t[22] + x20 * J_t[23] +
                   x21 * J_t[24] + x22 * J_t[25] + x23 * J_t[26];
  const auto x25 = x17 * J_t[28] + x19 * J_t[29] + x20 * J_t[30] +
                   x21 * J_t[31] + x22 * J_t[32] + x23 * J_t[33];
  const auto x26 = x17 * J_t[35] + x19 * J_t[36] + x20 * J_t[37] +
                   x21 * J_t[38] + x22 * J_t[39] + x23 * J_t[40];
  const auto x39 = x30 * J_t[21] + x31 * J_t[22] + x32 * J_t[23] +
                   x34 * J_t[24] + x36 * J_t[25] + x38 * J_t[26];
  const auto x40 = x30 * J_t[28] + x31 * J_t[29] + x32 * J_t[30] +
                   x34 * J_t[31] + x36 * J_t[32] + x38 * J_t[33];
  const auto x41 = x30 * J_t[35] + x31 * J_t[36] + x32 * J_t[37] +
                   x34 * J_t[38] + x36 * J_t[39] + x38 * J_t[40];
  const auto x51 = x45 * J_t[21] + x46 * J_t[22] + x47 * J_t[23] +
                   x48 * J_t[24] + x49 * J_t[25] + x50 * J_t[26];
  const auto x52 = x45 * J_t[28] + x46 * J_t[29] + x47 * J_t[30] +
                   x48 * J_t[31] + x49 * J_t[32] + x50 * J_t[33];
  const auto x53 = x45 * J_t[35] + x46 * J_t[36] + x47 * J_t[37] +
                   x48 * J_t[38] + x49 * J_t[39] + x50 * J_t[40];
  J_full[0] = x3 * J_bf[0] + x6 * J_bf[1] + x8 * J_bf[2];
  J_full[1] = x17 * J_bf[0] + x19 * J_bf[1] + x20 * J_bf[2];
  J_full[2] = x30 * J_bf[0] + x31 * J_bf[1] + x32 * J_bf[2];
  J_full[3] = x45 * J_bf[0] + x46 * J_bf[1] + x47 * J_bf[2];
  J_full[4] = 0;
  J_full[5] = x3 * J_bf[7] + x6 * J_bf[8] + x8 * J_bf[9];
  J_full[6] = x17 * J_bf[7] + x19 * J_bf[8] + x20 * J_bf[9];
  J_full[7] = x30 * J_bf[7] + x31 * J_bf[8] + x32 * J_bf[9];
  J_full[8] = x45 * J_bf[7] + x46 * J_bf[8] + x47 * J_bf[9];
  J_full[9] = 0;
  J_full[10] = x12 * J_bf[17] + x13 * J_bf[18] + x14 * J_bf[19] +
               x3 * J_bf[14] + x6 * J_bf[15] + x8 * J_bf[16];
  J_full[11] = x17 * J_bf[14] + x19 * J_bf[15] + x20 * J_bf[16] +
               x24 * J_bf[17] + x25 * J_bf[18] + x26 * J_bf[19];
  J_full[12] = x30 * J_bf[14] + x31 * J_bf[15] + x32 * J_bf[16] +
               x39 * J_bf[17] + x40 * J_bf[18] + x41 * J_bf[19];
  J_full[13] = x45 * J_bf[14] + x46 * J_bf[15] + x47 * J_bf[16] +
               x51 * J_bf[17] + x52 * J_bf[18] + x53 * J_bf[19];
  J_full[14] = 0;
  J_full[15] = x12 * J_bf[24] + x13 * J_bf[25] + x14 * J_bf[26] +
               x3 * J_bf[21] + x6 * J_bf[22] + x8 * J_bf[23];
  J_full[16] = x17 * J_bf[21] + x19 * J_bf[22] + x20 * J_bf[23] +
               x24 * J_bf[24] + x25 * J_bf[25] + x26 * J_bf[26];
  J_full[17] = x30 * J_bf[21] + x31 * J_bf[22] + x32 * J_bf[23] +
               x39 * J_bf[24] + x40 * J_bf[25] + x41 * J_bf[26];
  J_full[18] = x45 * J_bf[21] + x46 * J_bf[22] + x47 * J_bf[23] +
               x51 * J_bf[24] + x52 * J_bf[25] + x53 * J_bf[26];
  J_full[19] = 0;
  J_full[20] = x10 * J_t[46] + x11 * J_t[47] + x3 * J_t[42] + x6 * J_t[43] +
               x8 * J_t[44] + x9 * J_t[45];
  J_full[21] = x17 * J_t[42] + x19 * J_t[43] + x20 * J_t[44] + x21 * J_t[45] +
               x22 * J_t[46] + x23 * J_t[47];
  J_full[22] = x30 * J_t[42] + x31 * J_t[43] + x32 * J_t[44] + x34 * J_t[45] +
               x36 * J_t[46] + x38 * J_t[47];
  J_full[23] = x45 * J_t[42] + x46 * J_t[43] + x47 * J_t[44] + x48 * J_t[45] +
               x49 * J_t[46] + x50 * J_t[47];
  J_full[24] = 1;
}

template <typename T>
void boundToCurvilinearTransportJacobianImpl(const T* J_fb, const T* J_t,
                                             const T* J_bf,
                                             const T* step_path_derivatives,
                                             const T* dir, T* J_full) {
  const auto x0 = J_fb[5] * step_path_derivatives[1];
  const auto x1 = J_fb[10] * step_path_derivatives[2];
  const auto x2 = -dir[0] * step_path_derivatives[0] + 1;
  const auto x4 = J_fb[0] * step_path_derivatives[0];
  const auto x5 = -dir[1] * step_path_derivatives[1] + 1;
  const auto x7 = -dir[2] * step_path_derivatives[2] + 1;
  const auto x12 = J_fb[6] * step_path_derivatives[1];
  const auto x13 = J_fb[11] * step_path_derivatives[2];
  const auto x15 = J_fb[1] * step_path_derivatives[0];
  const auto x21 = J_fb[17] * step_path_derivatives[3];
  const auto x22 = J_fb[22] * step_path_derivatives[4];
  const auto x23 = J_fb[27] * step_path_derivatives[5];
  const auto x30 = J_fb[18] * step_path_derivatives[3];
  const auto x31 = J_fb[23] * step_path_derivatives[4];
  const auto x32 = J_fb[28] * step_path_derivatives[5];
  const auto x24 = (-x21 - x22 - x23) * dir[0];
  const auto x25 = (-x21 - x22 - x23) * dir[1];
  const auto x26 = (-x21 - x22 - x23) * dir[2];
  const auto x33 = (-x30 - x31 - x32) * dir[0];
  const auto x34 = (-x30 - x31 - x32) * dir[1];
  const auto x35 = (-x30 - x31 - x32) * dir[2];
  const auto x3 = -x0 * dir[0] - x1 * dir[0] + x2 * J_fb[0];
  const auto x6 = -x1 * dir[1] - x4 * dir[1] + x5 * J_fb[5];
  const auto x8 = -x0 * dir[2] - x4 * dir[2] + x7 * J_fb[10];
  const auto x14 = -x12 * dir[0] - x13 * dir[0] + x2 * J_fb[1];
  const auto x16 = -x13 * dir[1] - x15 * dir[1] + x5 * J_fb[6];
  const auto x17 = -x12 * dir[2] - x15 * dir[2] + x7 * J_fb[11];
  const auto x9 = x3 * J_t[21] + x6 * J_t[22] + x8 * J_t[23];
  const auto x10 = x3 * J_t[28] + x6 * J_t[29] + x8 * J_t[30];
  const auto x11 = x3 * J_t[35] + x6 * J_t[36] + x8 * J_t[37];
  const auto x18 = x14 * J_t[21] + x16 * J_t[22] + x17 * J_t[23];
  const auto x19 = x14 * J_t[28] + x16 * J_t[29] + x17 * J_t[30];
  const auto x20 = x14 * J_t[35] + x16 * J_t[36] + x17 * J_t[37];
  const auto x27 = x24 * J_t[21] + x25 * J_t[22] + x26 * J_t[23] +
                   J_fb[17] * J_t[24] + J_fb[22] * J_t[25] + J_fb[27] * J_t[26];
  const auto x28 = x24 * J_t[28] + x25 * J_t[29] + x26 * J_t[30] +
                   J_fb[17] * J_t[31] + J_fb[22] * J_t[32] + J_fb[27] * J_t[33];
  const auto x29 = x24 * J_t[35] + x25 * J_t[36] + x26 * J_t[37] +
                   J_fb[17] * J_t[38] + J_fb[22] * J_t[39] + J_fb[27] * J_t[40];
  const auto x36 = x33 * J_t[21] + x34 * J_t[22] + x35 * J_t[23] +
                   J_fb[18] * J_t[24] + J_fb[23] * J_t[25] + J_fb[28] * J_t[26];
  const auto x37 = x33 * J_t[28] + x34 * J_t[29] + x35 * J_t[30] +
                   J_fb[18] * J_t[31] + J_fb[23] * J_t[32] + J_fb[28] * J_t[33];
  const auto x38 = x33 * J_t[35] + x34 * J_t[36] + x35 * J_t[37] +
                   J_fb[18] * J_t[38] + J_fb[23] * J_t[39] + J_fb[28] * J_t[40];
  J_full[0] = x3 * J_bf[0] + x6 * J_bf[1] + x8 * J_bf[2];
  J_full[1] = x14 * J_bf[0] + x16 * J_bf[1] + x17 * J_bf[2];
  J_full[2] = x24 * J_bf[0] + x25 * J_bf[1] + x26 * J_bf[2];
  J_full[3] = x33 * J_bf[0] + x34 * J_bf[1] + x35 * J_bf[2];
  J_full[4] = 0;
  J_full[5] = x3 * J_bf[7] + x6 * J_bf[8] + x8 * J_bf[9];
  J_full[6] = x14 * J_bf[7] + x16 * J_bf[8] + x17 * J_bf[9];
  J_full[7] = x24 * J_bf[7] + x25 * J_bf[8] + x26 * J_bf[9];
  J_full[8] = x33 * J_bf[7] + x34 * J_bf[8] + x35 * J_bf[9];
  J_full[9] = 0;
  J_full[10] = x10 * J_bf[18] + x11 * J_bf[19] + x3 * J_bf[14] + x6 * J_bf[15] +
               x8 * J_bf[16] + x9 * J_bf[17];
  J_full[11] = x14 * J_bf[14] + x16 * J_bf[15] + x17 * J_bf[16] +
               x18 * J_bf[17] + x19 * J_bf[18] + x20 * J_bf[19];
  J_full[12] = x24 * J_bf[14] + x25 * J_bf[15] + x26 * J_bf[16] +
               x27 * J_bf[17] + x28 * J_bf[18] + x29 * J_bf[19];
  J_full[13] = x33 * J_bf[14] + x34 * J_bf[15] + x35 * J_bf[16] +
               x36 * J_bf[17] + x37 * J_bf[18] + x38 * J_bf[19];
  J_full[14] = 0;
  J_full[15] = x10 * J_bf[25] + x11 * J_bf[26] + x3 * J_bf[21] + x6 * J_bf[22] +
               x8 * J_bf[23] + x9 * J_bf[24];
  J_full[16] = x14 * J_bf[21] + x16 * J_bf[22] + x17 * J_bf[23] +
               x18 * J_bf[24] + x19 * J_bf[25] + x20 * J_bf[26];
  J_full[17] = x24 * J_bf[21] + x25 * J_bf[22] + x26 * J_bf[23] +
               x27 * J_bf[24] + x28 * J_bf[25] + x29 * J_bf[26];
  J_full[18] = x33 * J_bf[21] + x34 * J_bf[22] + x35 * J_bf[23] +
               x36 * J_bf[24] + x37 * J_bf[25] + x38 * J_bf[26];
  J_full[19] = 0;
  J_full[20] = x3 * J_t[42] + x6 * J_t[43] + x8 * J_t[44];
  J_full[21] = x14 * J_t[42] + x16 * J_t[43] + x17 * J_t[44];
  J_full[22] = x24 * J_t[42] + x25 * J_t[43] + x26 * J_t[44] +
               J_fb[17] * J_t[45] + J_fb[22] * J_t[46] + J_fb[27] * J_t[47];
  J_full[23] = x33 * J_t[42] + x34 * J_t[43] + x35 * J_t[44] +
               J_fb[18] * J_t[45] + J_fb[23] * J_t[46] + J_fb[28] * J_t[47];
  J_full[24] = 1;
}
